// Answers travel in the URL so a result can be shared without accounts or a
// server. Decoding validates every value against the question definitions, so
// a hand-edited link can't inject unexpected data.

import { type Answers, QUESTIONS, effectiveAnswers } from "./questions";
import { AUTONOMY, TOOLS, TOPOLOGIES } from "./catalog";
import type { Recommendation } from "./rules";

const MAX_TASK = 200;

function toBase64Url(s: string): string {
  const bytes = new TextEncoder().encode(s);
  let bin = "";
  bytes.forEach((b) => (bin += String.fromCharCode(b)));
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function fromBase64Url(s: string): string {
  const b64 = s.replace(/-/g, "+").replace(/_/g, "/") + "===".slice((s.length + 3) % 4);
  const bin = atob(b64);
  return new TextDecoder().decode(Uint8Array.from(bin, (c) => c.charCodeAt(0)));
}

export function encodeAnswers(a: Answers): string {
  return toBase64Url(JSON.stringify(a));
}

export function decodeAnswers(code: string): Answers | null {
  let raw: unknown;
  try {
    raw = JSON.parse(fromBase64Url(code));
  } catch {
    return null;
  }
  if (!raw || typeof raw !== "object") return null;
  const input = raw as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const q of QUESTIONS) {
    const v = input[q.id];
    if (v === undefined) continue;
    if (q.kind === "text") {
      if (typeof v === "string") out[q.id] = v.slice(0, MAX_TASK);
      continue;
    }
    const allowed = new Set(q.options!.map((o) => o.value));
    if (q.kind === "single" && typeof v === "string" && allowed.has(v)) out[q.id] = v;
    if (q.kind === "multi" && Array.isArray(v)) {
      const vals = [...new Set(v.filter((x): x is string => typeof x === "string" && allowed.has(x)))];
      if (vals.length) out[q.id] = q.exclusive && vals.includes(q.exclusive) ? [q.exclusive] : vals;
    }
  }
  return out as Answers;
}

/** Shared links carry only the answers that apply, never stale ones from an abandoned path. */
export function resultCode(a: Answers): string {
  return encodeAnswers(effectiveAnswers(a));
}

export function resultUrl(a: Answers, base = window.location.href): string {
  const url = new URL(base);
  url.hash = `/result?a=${resultCode(a)}`;
  return url.toString();
}

/** A plain-text version of the result, suitable for email, chat or a document. */
export function resultAsText(r: Recommendation, link?: string, steps?: string[]): string {
  const lines: string[] = [];
  const add = (...l: string[]) => lines.push(...l);
  const flow = [TOPOLOGIES[r.topology.primary].name, ...r.topology.addOns.map((t) => TOPOLOGIES[t].name)].join(", then ");

  add(`AGENT ARCHITECTURE GUIDE: STARTING ARCHITECTURE`);
  if (r.task) add(`Task: ${r.task}`);
  add("");
  add(`RECOMMENDATION`, r.approach.title, r.approach.summary, `Agents: ${r.approach.agents}`, "");
  if (steps?.length) add(`HOW IT FLOWS, STEP BY STEP`, ...steps, "");
  add(`SHAPE OF THE SYSTEM`, flow, ...r.topology.why.map((w) => `- ${w.text}`), "");
  add(`TOOLS`);
  for (const t of r.tools) add(`- ${TOOLS[t.tool].name}${t.core ? " (main tool)" : ""}: ${t.role}`);
  for (const h of r.hybrid) add(`- Hybrid: ${h.text}`);
  add(`- Hosting: ${r.hosting.title}. ${r.hosting.body}`, "");
  add(`AUTONOMY`, `Level ${r.autonomy.level} of 4: ${AUTONOMY[r.autonomy.level].name}. ${AUTONOMY[r.autonomy.level].plain}`);
  add(...r.autonomy.checkpoints.map((c) => `- ${c}`), "");
  if (r.models.needed) {
    add(`MODEL CAPABILITIES TO LOOK FOR`);
    add(...r.models.capabilities.map((c) => `- ${c.title}: ${c.body}`));
    add(r.models.examples, "");
  } else {
    add(`MODELS`, "No AI model is needed for this task.", "");
  }
  add(`SIMPLER WAY TO START`, `${r.simpler.title}. ${r.simpler.body}`, "");
  add(`GOTCHAS`, ...r.gotchas.map((g) => `- ${g.title}. ${g.body}`), "");
  add(`FIRST STEPS`, ...r.firstSteps.map((s, i) => `${i + 1}. ${s}`));
  if (link) add("", `View or change this result: ${link}`);
  add("", "Generated by fixed, published rules based on AI Assignment 4 research. Product names are examples and may change.");
  return lines.join("\n");
}
