import { describe, expect, it } from "vitest";
import type { Answers } from "../src/lib/questions";
import { resultCode } from "../src/lib/share";
import { TAILORED_LIMIT, clearTailored, fingerprint, loadTailored, putTailored, saveTailored, takeTailored } from "../src/lib/tailored";

function memory() {
  const m = new Map<string, string>();
  return { getItem: (k: string) => m.get(k) ?? null, setItem: (k: string, v: string) => void m.set(k, v), removeItem: (k: string) => void m.delete(k), m };
}

const emails: Answers = { task: "Answer routine customer emails", shape: "varies", kinds: "yes", roles: "one", quality: "partly", knowledge: ["playbook"], systems: "act", trigger: "event", volume: "daily", risks: ["visible"], location: "open", team: "mid" };
const generated = '{"name":"generated"}';
const tailored = { content: '{"name":"tailored"}', model: "gpt-6.1-sol" };

describe("saved AI tailoring", () => {
  it("keeps a tailored workflow for the same answers and generated workflow", () => {
    const s = memory();
    saveTailored(emails, generated, tailored, s, 1000);
    expect(loadTailored(emails, generated, s)).toMatchObject({ ...tailored, base: fingerprint(generated), savedAt: 1000 });
  });

  it("finds it again from answers that differ only in skipped questions", () => {
    const s = memory();
    saveTailored(emails, generated, tailored, s);
    expect(loadTailored({ ...emails, split: "sequential" }, generated, s)?.content).toBe(tailored.content);
  });

  it("drops it when the answers or the generated workflow change", () => {
    const s = memory();
    saveTailored(emails, generated, tailored, s);
    expect(loadTailored({ ...emails, task: "Something else" }, generated, s)).toBeUndefined();
    expect(loadTailored(emails, '{"name":"generated by newer rules"}', s)).toBeUndefined();
  });

  it("replaces an earlier tailoring of the same design", () => {
    const s = memory();
    saveTailored(emails, generated, tailored, s);
    saveTailored(emails, generated, { ...tailored, content: '{"name":"retailored"}' }, s);
    expect(loadTailored(emails, generated, s)?.content).toBe('{"name":"retailored"}');
  });

  it("keeps only the newest few", () => {
    const s = memory();
    for (let i = 0; i <= TAILORED_LIMIT; i++) saveTailored({ ...emails, task: `Task ${i}` }, generated, tailored, s, i);
    expect(loadTailored({ ...emails, task: "Task 0" }, generated, s)).toBeUndefined();
    expect(loadTailored({ ...emails, task: `Task ${TAILORED_LIMIT}` }, generated, s)).toBeDefined();
    expect(Object.keys(JSON.parse(s.m.get("aag:tailored")!))).toHaveLength(TAILORED_LIMIT);
  });

  it("can be taken out and put back, for deleting with Undo", () => {
    const s = memory();
    saveTailored(emails, generated, tailored, s);
    const taken = takeTailored(resultCode(emails), s);
    expect(loadTailored(emails, generated, s)).toBeUndefined();
    putTailored(resultCode(emails), taken!, s);
    expect(loadTailored(emails, generated, s)?.content).toBe(tailored.content);
  });

  it("survives broken or missing storage", () => {
    const s = memory();
    s.m.set("aag:tailored", "not json");
    expect(loadTailored(emails, generated, s)).toBeUndefined();
    expect(() => saveTailored(emails, generated, tailored, null)).not.toThrow();
    clearTailored(s);
    expect(s.m.has("aag:tailored")).toBe(false);
  });
});
